name: 'Create Bucket on GCP'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  gcp-create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
          export SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
          export SNOWFLAKE_AUTHENTICATOR=JWT
          export SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
          export SNOWFLAKE_PRIVATE_KEY=${{ secrets.SNOWFLAKE_PRIVATE_KEY }} 
          terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: |
          export SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
          export SNOWFLAKE_AUTHENTICATOR=JWT
          export SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
          export SNOWFLAKE_PRIVATE_KEY=${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          terraform apply -auto-approve
